version: '2'
services:
  torproxy:
    build: ./torproxy
    ports:
        # The socks5 proxy port exposed for the whole system
        - "9050:9050"
    network_mode: "host"
    privileged: true
  main:
    build: ./main
    depends_on:
        - torproxy
