FROM resin/%%RESIN_MACHINE_NAME%%-alpine

RUN apk add --no-cache tor curl

COPY torrc /etc/tor/

HEALTHCHECK --interval=60s --timeout=15s --start-period=90s \
            CMD curl --fail --socks5 localhost:9050 -I -L ipinfo.io || exit 1

ENV INITSYSTEM=on
RUN rc-update add tor
CMD tail -f /var/log/tor/notices.log
